### ISSUE TITLE
[Bug]: toMap is recommended in the documentation, but deprecated without an apparent replacement

### ISSUE THREAD

**Issue by BernieSumption** [fluttercommunity/plus_plugins#1291]
### Platform

iOS 16

### Plugin

device_info_plus

### Version

7.0.1

### Flutter SDK

3.3.4

### Steps to reproduce

The [documentation](https://pub.dev/packages/device_info_plus) recommends that in order to get all available device information in a platform-agnostic way, the `toMap()` method should be used. This been deprecated with no apparent replacement.

I'm not sure if this is a bug report that the recommended method has been deprecated, or a feature request that a non-deprecated method be provided!

In any case, in the mean time I have downgraded to 6.0.0 so that I can use the toMap method without warnings.

### Code Sample

```dart
final deviceInfoPlugin = DeviceInfoPlugin();
final deviceInfo = await deviceInfoPlugin.deviceInfo;
final allInfo = deviceInfo.toMap();
```

### Logs

```shell
n/a - compile time error
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-arm, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

### Checklist before submitting a bug

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Should be removed from the documentation, then.

The problem with `toMap` is that it is not a JSON compatible object as it contains non-serializable data, being misleading to users, and that's why it is currently being deprecated.

The alternative is to read each value individually and build your own data class.

The device_info_plus package needs a deep refactor, so we cannot promise if the `toMap` is going to stay in the future, and we don't know yet what to do to replace it, that's why it is marked as deprecated and use at your own risk.

**Comment by miquelbeltran** [comment]
FYI @BernieSumption the `toMap()` method is replaced by the `data` member of the `BaseDeviceInfo` class
