### ISSUE TITLE
[Question]: Problem with NetworkInfo().getWifiIP(); return null on iPhone 14 Pro and iOS 16.3.1 

### ISSUE THREAD

**Issue by juanjuliocorica** [fluttercommunity/plus_plugins#1652]
### What is your question?

Hi,
I need help to solve the problem because I have already searched everything and tried everything I could and I can't get the app to work correctly on iphone 14 pro devices with iOS 16.3.1

The problem occurs in the function that returns the IP of the Wi-Fi network NetworkInfo().getWifiIP().
I tried adding more permissions via plist.info but it still doesn't work.
It always returns a null value.

The code snippet I use is very simple:

`Future<Estados> _verificarConexionWifi() async {
    ipAddress = await NetworkInfo().getWifiIP();
    if (ipAddress == null) {
       estadoDeConexion = Estados.sinWifi;
    }
    return estadoDeConexion;
}`

The app has been published for a long time and we have no reports of problems on other devices.
I asked Apple to allow me permission to use multicast messages just in case, but it did not solve the problem.

I don't know what else to do and that is why I am writing to see if something similar is happening to someone and they already solved it to find out how they did it.

Thank you very much in advance for any help you can give me.

Unfortunately I don't have the debug log because we don't have an iphone 14 Pro and with the devices we have we can't recreate the problem.

### Checklist before submitting a question

- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
> Do you think it could be the name of the WiFi network that is no longer en0?

Thanks for reporting and providing additional information. It might be that the issue is indeed in this change. Will try to look at it soon.

**Comment by juanjuliocorica** [comment]
thank you!  Unfortunately I don't have a physical iPhone 14 pro to debug and send you more information or a possible solution.  keep in touch.

**Comment by kvinltf** [comment]
Hi, also faced this issues on my iPad Mini 6th gen, but its working fine on my iPhone

iPhone 14 Pro, iOS 16.3.1
![Screen Shot 2023-05-09 at 4 23 18 PM](https://user-images.githubusercontent.com/10257886/237038504-25668391-7f6b-4d9b-a21a-aa3dc0a4e187.png)

iPad mini 6th, iPadOS 16.2
![Screen Shot 2023-05-09 at 4 23 22 PM](https://user-images.githubusercontent.com/10257886/237038752-af257a16-52ae-437d-afca-b20d806d3cc9.png)

**Comment by juanjuliocorica** [comment]
Thank you kvinltf for your contribution to the topic.
If you know how to modify the code of the interface for iOS you could do some tests modifying the library.
I tried blindly because I didn't have a physical device with the problem and couldn't solve it.
I'm still looking for how to solve it.

**Comment by smunoz-ml** [comment]
I'm having this issue as well. This only happens in my Mac mini M1 with the emulator (iOS 16.4). My boss has a 2019 MBP and doesn't have this issue with the emulator.

**Comment by juanjuliocorica** [comment]
Hi, I wanted to inform you that we already have 4 users with the same problem and they all have iPhone 14 pro max.
Could anyone solve the problem?

**Comment by salmaahhmed** [comment]
Having the same problem

**Comment by Skyost** [comment]
Same problem here running on a iOS Simulator (iPhone 14 Pro Max). Any news ?

**Comment by porum** [comment]
facing the same problem, any update?

**Comment by Skyost** [comment]
This issue still exist.

**Comment by Skyost** [comment]
Still unsolved.

**Comment by vbuberen** [comment]
@Skyost I would suggest to check out this discussion https://github.com/fluttercommunity/plus_plugins/issues/2156#issuecomment-1994382601 as I believe that it is the same problem here.

**Comment by indeedshaw** [comment]
Any solution?Facing getWifiIp will null，not wifiName and BSSID.

**Comment by mrcendre** [comment]
This issue does not seem correlated to a specific model or iOS version. It is likely to be caused by hardware-level differences between device components — different WiFi chips or firmwares for example. Anyways, an Apple engineer explains the following about the "en0" naming in [this thread](https://forums.developer.apple.com/forums/thread/49581) :

> Those names are not considered API. Right now, **there is no reliable way to determine which interface fulfils which user-level role**.

The problem here is that the `en0` network interface expected by the plugin, which according to many StackOverflow posts is "supposed to be the WiFi interface on all iOS devices", **has no IP address**.

Rather, the WiFi address is available on the `en2` interface, indicating that the WiFi interface is not `en0` but `en2`.

Here is the list of `en` interfaces and their addresses, on iPhone 14 Pro which successfully reproduces the issue (ie. where `getWifiIP` returns `null`), running iOS 17.6.1 with no VPN configured :

```yaml
Interface: en0 - Address: 02:00:00:00:00:00
Interface: en1 - Address: 02:00:00:00:00:00
Interface: en2 - Address: 02:00:00:00:00:00
Interface: en2 - Address: fe80::10fc:cc47:1033:5635%en2
Interface: en2 - Address: 10.1.120.4
```

As you can tell, `en0` has no valid IP address but `en2` does.

A possible solution would be to iterate over network interfaces that have the "en" prefix, until a non-nil address is returned. Here would be the updated version of the `enumerateWifiAddresses:usingBlock:` implementation :

```diff
/packages/network_info_plus/network_info_plus/ios/Classes/FPPNetworkInfoPlusPlugin.m

@@ -68,7 +68,8 @@

   __block NSString *addr = nil;
   [self enumerateWifiAddresses:AF_INET
                     usingBlock:^(struct ifaddrs *ifaddr) {
+                      if (addr) return; // Pick the first valid address
                       addr = [self descriptionForAddress:ifaddr->ifa_addr];
                     }];
   return addr;

@@ -145,8 +146,8 @@

       if (temp_addr->ifa_addr->sa_family == family) {
-         // en0 is the wifi connection on iOS
+         // The WiFi interface on iOS has the "en" prefix
         if ([[NSString stringWithUTF8String:temp_addr->ifa_name]
-                isEqualToString:@"en0"]) {
+                hasPrefix:@"en"]) {
           block(temp_addr);
         }
       }
```

@vbuberen This implementation fixes the issue and returns the right IP address for the WiFi interface. Unfortunately, I have no detailed information as to why interface names is not consistent between devices.

**Comment by arthas1888** [comment]
I have the same issue but my iPhone is 13 iOS version 18.2
as ypu can see wifiname and bssid is well, the others params are always null
`
flutter: ------------- wifiName QoriKenjiNet ---------
flutter: ------------- wifiBSSID 42:ae:30:21:dc:3b ---------
flutter: ------------- wifiIP null ---------
flutter: ------------- wifiIPv6 null ---------
flutter: ------------- wifiSubmask null ---------
flutter: ------------- wifiBroadcast null ---------
flutter: ------------- wifiGateway null ---------
flutter: ------------- subnet  ---------
`

**Comment by mrcendre** [comment]
> I have the same issue

@arthas1888 So will many other random iOS devices until the fix to support `en*` (if relevant) is applied by a *plus_plugin* maintainer and makes its way into a public release of the package.

In the meantime, if fixing this is critical for your project, you can use a forked version of the plugin where you include the fix yourself, or add a patching logic to your Podfile's post install section — which is discouraged since it's very hacky.

**Comment by vbuberen** [comment]
Thanks for bumping this issue with comments as I missed it in my inbox in September. Thanks a lot for a suggestion with a possible solution along with resources on where it comes from. Very valuable. Curios why there were no PR so far, but I will fix it after some addition testing and research 🙂

**Comment by arthas1888** [comment]
> Thanks for bumping this issue with comments as I missed it in my inbox in September. Thanks a lot for a suggestion with a possible solution along with resources on where it comes from. Very valuable. Curios why there were no PR so far, but I will fix it after some addition testing and research 🙂

thanks

**Comment by marcos930807** [comment]
https://github.com/fluttercommunity/plus_plugins/pull/3408#issuecomment-2777451912

**Comment by mrcendre** [comment]
Hi @marcos930807, could you provide the full list of network interfaces returned on this device?

As a reminder, on iOS, there is no way to tell _"which interface is the current WiFi's interface"_, since the interface names/orders are subject to change from one iPhone to the other — even two iPhones of the same model can have a different network interface layouts.

Both IP addresses obtained with the two implementations are valid, they're just in different ranges. Thus, it seems that the only way to determine which one is the right address would be to check what ranges they belong to, which the package does not currently implement.

When #420 lands, you could be able to retrieve all network interfaces and add your own address-picking logic to your application.
