### ISSUE TITLE
[share] java.lang.ClassCastException when sharing multiple files at once (non-breaking)

### ISSUE THREAD

**Issue by nt4f04uNd** [fluttercommunity/plus_plugins#176]
see https://github.com/flutter/flutter/issues/77361

**Comment by mhadaily** [comment]
go for it @Boehrsi

**Comment by Boehrsi** [comment]
@mhadaily I investigated the problem and the fix is actually quite easy, but it comes with a huge draw back (see below). In general the question is should we change something or should we change nothing. A bonus question is if I should at least add a PR with code comments explaining the situation.

**TLDR**
We should probably change nothing and just live with the exception.

**Actual problem:**
If `ACTION_SEND_MULTIPLE` is used we shouldn't deliver one string with text, but an `ArrayList<String>` matching the size of the delivered URIs.  Doing this is easy and I tried it (the exception was fixed). But the problem is I found no receiving app handling this. Even the default Android messaging app just ditched my text, if it was supplied via the ArrayList and everything was working fine with the single string + exception. This means if we fix the exception we will break the multi share + text feature for most apps.

**General information:**
We are using https://developer.android.com/reference/android/content/Intent.html#ACTION_SEND_MULTIPLE and normally `ACTION_SEND_MULTIPLE` shouldn't contain the `EXTRA_TEXT` field at all, as we are supplying `EXTRA_STREAM` and only one of those should be set. But it works, so probably removing it isn't a good idea.

**Comment by mhadaily** [comment]
alright, do you mean that `ArrayList<String>` is not supported in any versions on Android? 

it seems there are suggestion related to this for example https://stackoverflow.com/a/15577579/1921541

**Comment by Boehrsi** [comment]
It's supported and it compiles fine. Code and Android wise everything is okay.

The problem is:
We are preparing the Intent and then it's delivered to other apps on the device. The user chooses one app and this external app then parses the Intent. Those receiving apps seem not to implement handling for a list of message strings for the `EXTRA_TEXT` field. They only handle the case with one String. The result is that the share works (the files are visible), but the text is missing. And as already written this is even the case with e.g. the default Messenger app, so we probably can't assume other app developers have implemented list handling for this field.

**Comment by mhadaily** [comment]
alright, then what we can do is to release a new Major version (breaking change) and explain the new requirement. what do you think?

**Comment by Boehrsi** [comment]
Yeah this is an option, but I think it could be a better idea to live with the currently working setup and keep the invisible and non-breaking exception.
In general I would always favor a clean, exception free and structured solution, but in this case I would rather keep the current setup.
The reason is that we currently have a working setup, which isn't beautiful, but it fits the real world requirements. The whole Intent and sharing area is a bit problematic on Android system side due to legacy stuff, not completely clear documentation and other small things. Because of that currently release apps are handling stuff the way they to. Not the way the documentation says, but the way that pleases the user. I'm pretty sure that even with a major version update and good documentation "why we did those changes" multiple bugs would occur if users aren't apple to share images + text with e.g. Whatsapp suddenly.
Not the most satisfactory solution, but a fitting one I would say.

**Comment by mhadaily** [comment]
Makes sense. 
However, how can people now share multiple files? that's actually an issue right now I believe we have several open issues related to this.

**Comment by Boehrsi** [comment]
The sharing works completely fine right now, e.g. with the example app. The subject, text and all files are successfully shared with most other apps. The exception is thrown but doesn't crash anything.

There are other issues related to sharing but those aren't directly related to this problem. I saw some of the other issues where sharing with specific apps weren't possible. Those apps probably implement the parsing of the shared Intent a little bit different and therefore it breaks. Due to the unclear overall situation (Android system wise) I think we can just look into the specific issues one by one and some of them probably shouldn't be fixed here in the plugins, but in the apps parsing the shared data. The whole sharing area is a pretty ungrateful topic as it's more or less impossible to provide "one setup working with all apps".

**Comment by mhadaily** [comment]
I think I would agree with you at the moment. 

let's keep it as is for now until we find a better solution. 

thanks for debugging.

**Comment by Boehrsi** [comment]
Sure thing, planned to help here a long time ago and finally found the trigger with the Hacktoberfest. I will have a look for some other issues and if I find some Android related sharing ones where I can help, I happly will.
If I encounter Android news in regards to this topic I will contact you if some sharing rewrites could be feasible in the future.
