### ISSUE TITLE
[share_plus] know when the sharing is finished

### ISSUE THREAD

**Issue by csacchetti** [fluttercommunity/plus_plugins#186]
I ask if there is a chance to know when the sharing is finished and the sharing window closes.
If this is not possible you could add this callback
Thanks for your valuable work

**Comment by ueman** [comment]
You can simply await the sharing.

Knowing when it finished or if it was done at all is not possible. The underlying platforms don't allow it.

**Comment by netgfx** [comment]
@ueman What do you mean the platforms don't allow it?

On iOS there is a clear function that does that `https://developer.apple.com/documentation/uikit/uiactivityviewcontroller/1622022-completionwithitemshandler`

**Comment by ueman** [comment]
It states that `The completion handler to execute after the activity view controller is dismissed.` which means that it also fires when the user did not share anything and just dismissed the dialog. It does say whether the user clicked an app icon or not, but it's basically meaningless because it does not take into account if the action in the receiving application was actually finished.

For example, imagine you are sharing an image to the Twitter app. The app allows you to add a tweet (text) to the image. As soon as the user is in the Twitter app, the completion handler would return true (indicating a successful share action), but the user didn't actually has shared it yet as he can still abort the process in the Twitter app.

The same applies to Android.

**Comment by netgfx** [comment]
Good point, however it is not because the platforms don't allow it, but because the different Apps don't return anything meaningful / or anything at all in order to be captured by the various callbacks. Or perhaps because the Apps don't really know what to return that would make sense to the callback.

**Comment by pawelsa** [comment]
On android, we can listen to the result in the `BroadcastReceiver`. I thought that using some kind of eventBus could be used to call `result.success`. 
I am not an iOS developer, so take this with a grain of salt. The handler @netgfx proposed has `activityType` and `complete` which looks like it could be useful to determine if the user performed an action. 

If this seems reasonable I could try to implement the solution for android, but I will leave iOS for someone else, as reading objective-c hurt my brain.
