### ISSUE TITLE
[share_plus] Dependency resolution issue

### ISSUE THREAD

**Issue by britannio** [fluttercommunity/plus_plugins#21]
Because share_plus >=1.1.0 depends on share_plus_windows ^1.0.0 which doesn't match any versions, share_plus >=1.1.0 is forbidden.

Seems like share_plus should depend on share_plus_windows ^0.1.0 or share_plus_windows 1.0.0 should be published.

**Comment by miquelbeltran** [comment]
Hi @britannio for what I can see share_plus depends on share_plus_windows ^0.1.0: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/share_plus/pubspec.yaml#L26.

However when I import the project, the same issue can be observed.

I tried to release share_plus 1.1.1 which depends on share_plus_windows ^0.1.0 yet the same issue is observed.

Maybe someone else can clarify why this issue is happening.

**Comment by jpnurmi** [comment]
Does it need some specific platform or Flutter version? I tried Windows, Linux, and Android, but had no issues. I'm on the dev channel.

**Comment by miquelbeltran** [comment]
Not happening to me any more too.

I added  `share_plus: ^1.1.1` to a project and pub get worked well.

Maybe was a caching issue? I will close this meanwhile, please reopen it if the issue persist.
