### ISSUE TITLE
[ci] clang-format hangs

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/plus_plugins#223]
running `melos run format` hangs in the `clang-format` part. This also happens locally on my Linux PC.

I am not sure how to disable that, but also the tool we are using (flutter_plugin_tools) is deprecated.

**Comment by stuartmorgan** [comment]
> I am not sure how to disable that, but also the tool we are using (flutter_plugin_tools) is deprecated.

FYI we'll be walking this deprecation back slightly, and the package will be updated soon to reflect the new plan. It will continue to be supported as a package since it's used in multiple flutter/* repositories, it just won't be explicitly supported as a general-purpose tool. I wouldn't expect any issues with continuing to use the tool's `format` command here.

**Comment by mhadaily** [comment]
@stuartmorgan thank you for heads-up

@miquelbeltran seems the latest PR has fixed the format issue. could you confirm and then close this issue?

**Comment by miquelbeltran** [comment]
yes, I think it is fine now!
