### ISSUE TITLE
[Question]: build ios problem

### ISSUE THREAD

**Issue by Prabha10cs** [fluttercommunity/plus_plugins#2243]
### What is your question?

[!] CocoaPods could not find compatible versions for pod "connectivity_plus":
  In Podfile:
    connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)

Specs satisfying the `connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)` dependency were found, but they required a higher minimum deployment target.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by heshesh2010** [comment]
+1

**Comment by vbuberen** [comment]
Have you read the changelog for `connectivity_plus: 5.0.0`? Min iOS is 12 now to not crash when app is built with Xcode 15. If your project has lower deployment target (as it highly likely considering the text of the error you shared) you need to bump it or use older version of `connectivity_plus`.

**Comment by LambGe** [comment]
+1

**Comment by vbuberen** [comment]
> +1. My project supports at least 12, but it still crashes.

+1 on what? Do you see that this issue is about the person clearly having the problem with versions compatibility, not about some crash. If you experience crash with connectivity_plus 5.0.0 then open a new bug report and fill in the template.

To all the downvoters - would be much better if any of you opened a proper bug report and filled in the information asked by a template in case you experience some issue with connectivity_plus 5.0.0. If you are downvoting because you have exactly the same problem as mentioned by the person asking the question - well, sorry for you if you can't read the error which is clearly stated by IDE about need to set minimum deployment target for iOS (which is also explicitly mentioned in the changelog for 5.0.0 release). I would only advise you to use Google more and learn what this error in IDE means and how to fix it.

**Comment by vbuberen** [comment]
@Prabha10cs Any updates?

**Comment by Prabha10cs** [comment]
I am changed minimum deployment version now it's working

**Comment by vbuberen** [comment]
Thanks for your feedback. Closing as completed

**Comment by ruchita-smartXR** [comment]
![Screenshot 2023-11-14 at 4 10 34 PM](https://github.com/fluttercommunity/plus_plugins/assets/150015519/3ac4f98d-3863-4631-b442-9c726a2d2c1a). 


[!] CocoaPods could not find compatible versions for pod "connectivity_plus":
  In Podfile:
    connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)

Specs satisfying the `connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)` dependency were found, but they required a higher minimum deployment target.

my verison is also alright 
what need to be done

**Comment by cqueen** [comment]
If you were like me and ended up here trying to figure out why you were still getting the error after setting the deployment target to 12, here's what worked for me: 
- In your Flutter project, navigate to your ios directory and open your "Podfile"
- If your "platform :ios," line not commented out and is lower than 12 because you specified a global platform for your project, increase it to at least 12.

**Comment by erkankavas** [comment]
yeah change version to 4.0.0 it works. for me.
