### ISSUE TITLE
[Question]: Why was kotlin_version bumped in latest version of device_info_plus, package_info_plus?

### ISSUE THREAD

**Issue by Jordan-Nelson** [fluttercommunity/plus_plugins#2245]
### What is your question?

Hey folks - I was hoping to get some context as to why kotlin_version was bumped in the latest version of a few packages (in particular device_info_plus and package_info_plus). I tried to get some context from the PRs to bump the version. There was some discussion about it here: https://github.com/fluttercommunity/plus_plugins/pull/2134

Is there an issue this resolves, or a feature that required this?

Flutter projects created with the latest stable/beta versions default to kotlin 1.7.10. I would think it would make sense to stick with that version of kotlin unless there was a good reason to force a higher version on consumers.

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Jordan-Nelson** [comment]
I also wanted to note that while connectivity_plus also states this as a breaking change, I was able to successfully compile an app with connectivity_plus and kotlin 1.7.10. It doesn't seem like connectivity_plus has a kt version in the [build.gradle](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/android/build.gradle) file as the plugin is written in java.

**Comment by jnelle** [comment]
I'm getting since the last update the following error message

```dart
error: cannot find symbol
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.packageinfo.PackageInfoPlugin());
```

**Comment by vbuberen** [comment]
> Is there an issue this resolves, or a feature that required this?

It is a matter of preference. PRs with Kotlin bump were already merged. I didn't want to roll them back, so introduced a breaking change release as knew about problems that Kotlin 1.8.x introduces for projects with both new and old Kotlin versions available

> Flutter projects created with the latest stable/beta versions default to Kotlin 1.7.10. I would think it would make sense to stick with that version of kotlin unless there was a good reason to force a higher version on consumers.

Yes, it is good idea, but it is up to maintainers of packages to decide which versions to use. In this case we had latest Kotlin version already merged and I am as a maintainer of Plus Pluginsis totally Ok with that as believe that projects should stick to modern versions.
Idea is the same as with not providing support for Android Gradle Plugin before versions 4.2 recently from Plus Plugins - I would like to see people moving their Flutter projects to latest versions of Android related dependencies. 
If it doesn't work for you - use older versions.

But for future releases I asked other active maintainers to not merge these Android related Dependabot PRs that fast to not need to introduce breaking changes again, especially since Kotlin releases 1.8.x brought issues to users with dependencies with older Kotlin versions.

> I also wanted to note that while connectivity_plus also states this as a breaking change, I was able to successfully compile an app with connectivity_plus and kotlin 1.7.10. It doesn't seem like connectivity_plus has a kt version in the [build.gradle](https://github.com/fluttercommunity/plus_plugins/blob/main/packages/connectivity_plus/connectivity_plus/android/build.gradle) file as the plugin is written in java.

Good catch. Our mistake during changelog generation.

**Comment by vbuberen** [comment]
There is no further space for discussion as I am not looking for advises on releases strategy for Plus Plugins, so closing this one as answered.

**Comment by vbuberen** [comment]
> I'm getting since the last update the following error message

Open another issue and provide all the required info as your comment isn't related to the question.

**Comment by Tienisto** [comment]
Is there an issue or discussion board about the release strategy?

**Comment by vbuberen** [comment]
> Is there an issue or discussion board about the release strategy?

There is already an answer provided above. No, there is no discussion or issue and no plans for it.

**Comment by vbuberen** [comment]
Update: Latest breaking changes will be retracted for every plugin except `connectivity_plus` due to https://github.com/fluttercommunity/plus_plugins/issues/2251
