### ISSUE TITLE
[Bug]: Android build failures

### ISSUE THREAD

**Issue by vbuberen** [fluttercommunity/plus_plugins#2251]
### Platform

Android

### Plugin

share_plus, device_info_plus

### Version

8.0.0 for share_plus and 10.0.0 for device_info_plus

### Flutter SDK

3.13.4

### Steps to reproduce

Tried to just update plugins in one of projects I work on.
Project uses fresh dependencies and has Kotlin 1.8.20 and AGP 7.4.2, so it is not an issue with some old Android native dependencies.

`flutter clean` didn't help.

Tried to find something similar and found that `mobile_scanner` also has a similar issue https://github.com/juliansteenbakker/mobile_scanner/issues/729 and it is also related to Kotlin 1.9.x

Not sure about the solution, but I also found [this page](https://developer.android.com/build/kotlin-support) where it is stated that for Kotlin 1.9 project needs to have AGP 8.0.

Based on this fact I am thinking about retracting latest versions of plugins that have Kotlin 1.9.10 and would like to revert Kotlin to older version to not have such unexpected failures that can't be reproduced by building available example apps.

### Logs

```shell
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform kotlin-stdlib-1.9.10.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.10) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/vb/.gradle/caches/transforms-3/28d185a8757e9cd8ecae045e483e8213/transformed/jetified-kotlin-stdlib-1.9.10.jar.
         > Error while dexing.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-UA)
    • Flutter version 3.13.4 on channel stable at /Users/vb/fvm/versions/3.13.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (4 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vb/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
    • IntelliJ at /Users/vb/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
@nohli FYI

**Comment by nohli** [comment]
Have you tried the changes I had to make in this PR?
https://github.com/fluttercommunity/plus_plugins/pull/2134

Idk what's better - reproduce the fix, and write it in a migration guide, including a breaking change, or just downgrade to kotlin 1.8.20.

Either way, retracting the latest versions would make sense.

**Comment by vbuberen** [comment]
> Have you tried the changes I had to make in this PR?
https://github.com/fluttercommunity/plus_plugins/pull/2134

You mean to try them in that project with problem? It is already using everything latest, including targeting Java 17 for a few months already. These changes have nothing to do with `R8` error (as from logs the error is pointing at R8).

I have already retracted versions, will open a PR with rollback of Kotlin updates and will release updates tomorrow with rollback as some plugins had other changes which are useful to users of plugins.

But I really hate what Google and Jetbrains did in their latest Kotlin and AGP releases - too many problems. Earlier it was much safer to update.

**Comment by milindgoel15** [comment]
downgrading kotlin to 1.8.10 would have been enough imo

**Comment by EchoEllet** [comment]
FYI, I also do prefer to use the latest versions of frameworks, languages, and all technologies when possible, I do use `java.nio.Path` and `java.nio.Files` instead of `java.io.File`. On Android, I do make sure to use the latest API on newer devices even if it doesn't solve an issue or provide a fix, or improvements, I used Android since Java and XML days, and I always to update the `kotlin` version, I also use `libs.gradle.versions` (Gradle version catalogs) and always latest version of Gradle.

So I think this is something we have in common, I have encountered many issues in production mode for Flutter applications when using Kotlin version higher than the default (currently is `1.8.22`, was `1.7.10`) which is `1.9.10` back when it just released in 2023 and I saw many issues, random crashes and many more, most of them require extensive amount of time to debug, notice that this is not issue related to R8 ([D8 and R8 compiler versions required for Kotlin versions](https://developer.android.com/build/kotlin-support#:~:text=R8%20can%20only%20emit%20Kotlin,newer%20R8%20preserves%20the%20version.)) since I disabled shrinking and obfuscation, and I only got different errors with the same behavior or similar, they don't feel familiar to those issues encountered when using Proguard with missing rules or configurations. Their optimizations are already disabled.

The user can always use the latest version of their project instead of having it in the Gradle module of the plugin, updating the minimum Kotlin version can introduce issues other than compatibility and I have seen some reported issues even outside of Flutter repo.

> But I really hate what Google and Jetbrains did in their latest Kotlin and AGP releases

Their changes backward compatible with native Android and Kotlin/JVM projects so it's might not be an issue directly related to their changes.

> Earlier it was much safer to update.

That depend on the changes and Flutter.
