### ISSUE TITLE
iOS privacy manifest required for several plugins

### ISSUE THREAD

**Issue by stuartmorgan** [fluttercommunity/plus_plugins#2447]
### Plugin

Various

### Use case

Several of this project's plugins are listed on on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest:
- connectivity_plus
- device_info_plus
- package_info_plus
- share_plus

See https://github.com/flutter/flutter/issues/131940 for context, but some kind of action will need to be taken.

If you've had any communication from Apple about what the expectations are for the plugins in terms of describing usage, that may be helpful as we work to understand the overall ecosystem impacts here.

### Proposal

Add privacy manifests, and/or clarify with Apple about whether these plugins should actually be on the list.

**Comment by AmirJV1** [comment]
@stuartmorgan  does this affects me if I'm planning on using this plugin for developing an ios app? if yes, what workaround do you suggest?

**Comment by ShuheiSuzuki-07** [comment]
Hello!

What is the status of the response to this matter?
You may need an empty manifest even if you are not collecting anything 😭
https://github.com/flutter/flutter/issues/131940#issuecomment-1881641272

If an empty manifest is ok I may be able to create a PR for you too.

**Comment by yuki43min** [comment]
My app  uses `share_plus` . There is a possibility of being rejected in the App Store review next spring.
Can someone please tell me what privacy information it is accessing?

**Comment by miquelbeltran** [comment]
Interesting that some of them are listed, but not all of them. I guess due to popularity.
Ideally, we will want to do this for all plugins, not only the ones listed.

This PR from the Flutter team could be a good starting template for this: https://github.com/flutter/packages/pull/5846

My understanding is that, since the plugins don't collect any data/send it anywhere, an empty manifest would be enough. Anyone else thinks the same?

**Comment by miquelbeltran** [comment]
I am taking care of this, will open a separate PR per plugin.

**Comment by stuartmorgan** [comment]
> My understanding is that, since the plugins don't collect any data/send it anywhere, an empty manifest would be enough. Anyone else thinks the same?

If any of the plugins in this repository use [a Required Reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api), that would require a non-empty manifest even if the plugin doesn't have any [data use](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) to declare.

**Comment by miquelbeltran** [comment]
Thanks @stuartmorgan 

Looking at the Flutter repo, the only plugin that used a Required Reason API was the `shared_preferences`, since it uses `UserDefaults`.

Taking a quick look over the Required Reason API, I couldn't find any that is used here in the plus plugins:
- `UIDevice` which is used in `device_info_plus` seems ok.
- Same for the network APIs used for `network_info_plus`.

In case we need to correct this in the future, the manifests will be in place, and can be updated accordingly.

**Comment by miquelbeltran** [comment]
Privacy info has been added to all plugins.

**Comment by miquelbeltran** [comment]
There is some info regarding upcoming releases here: https://github.com/fluttercommunity/plus_plugins/issues/2653
