### ISSUE TITLE
[Bug]: Share.shareWithResult throws exception on Android 11

### ISSUE THREAD

**Issue by lukepighetti** [fluttercommunity/plus_plugins#2515]
### Platform

Android 11 only

### Plugin

share_plus

### Version

7.2.1

### Flutter SDK

3.18.0-0.2.pre • channel beta

### Steps to reproduce

1. Share.shareWithResult on Android 11

### Logs

```shell
x
```

### Flutter Doctor

```shell
x
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Thanks for reporting, but it is really non-informative report. No logs, no explanations. Would you mind providing more info like exception details, etc.?

I looks to me like something that might be related to a few other issues we have opened and which might be fixed by one of currently opened PRs which waits for more tests.

**Comment by LBYPatrick** [comment]
1. As @vbuberen suggests, more information would be nice!
2. As it's been two months now, maybe running ``flutter upgrade && flutter clean && flutter pub get`` will magically fix the issue (as there are version updates since 7.2.2 rolled out since this was posted, and sometimes fix bugs without noticing or forgot to document)
3. What kind of Android are you using exactly? If it's some outside-of-flutter exception, it is also possible that the software vendor left something un-implemented (And the error message will explicitly state this is the case --> one of the reasons logs are helpful). I've seen this happening to Huawei devices few years ago when my Google & Xiaomi devices worked flawlessly
4. Share the code snippet you have for invoking the ``Share.shareWithResult`` API. Did you share a file? An image? Some random text? And did you check the validity of the content you are trying to share?

**Comment by vbuberen** [comment]
Closing as no info was provided.

There is also an assumption that it was fixed by #2817
