### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by c-seeger** [fluttercommunity/plus_plugins#2626]
### Platform

web

### Plugin

package_info_plus

### Version

5.0.1

### Flutter SDK

3.0.0

### Steps to reproduce

use http 1.2.1 and package_info_plus ^5.0.1 in the same project

### Code Sample

```dart
Because no versions of package_info_plus match >5.0.1 <6.0.0 and package_info_plus 5.0.1
  depends on web >=0.3.0 <0.5.0, package_info_plus ^5.0.1 requires web >=0.3.0 <0.5.0.
And because http >=1.2.1 depends on web ^0.5.0, package_info_plus ^5.0.1 is incompatible with
```

### Logs

```shell
-
```

### Flutter Doctor

```shell
-
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by Dgolme1** [comment]
Facing the same issue. Happened after a cleared my pub cache and updated. Hopefully this will be fixed soon!

**Comment by miquelbeltran** [comment]
Fixed in https://github.com/fluttercommunity/plus_plugins/pull/2605

Please use the search function before opening issues, as this has already been discussed.

You can also use [git ref](https://dart.dev/tools/pub/dependencies#git-packages) to reference a specific commit in your pubspec.yml, so you don't have to wait for a package release.
