### ISSUE TITLE
[Bug]: It's not clear what appName actually means on desktop platforms

### ISSUE THREAD

**Issue by Hixie** [fluttercommunity/plus_plugins#2842]
### Platform

linux, macos, windows

### Plugin

package_info_plus

### Version

7.0.0

### Flutter SDK

3.22.0-11.0.pre.14

### Steps to reproduce

The documentation for appName:
   https://pub.dev/documentation/package_info_plus/latest/package_info_plus/PackageInfo/appName.html
...doesn't say what it does anywhere other than iOS and Android.

I expected to get the same result on Windows, macOS, and Linux, and did not.

### Logs

```shell
n/a
```

### Flutter Doctor

```shell
n/a
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Is your report about the lack of documentation, or about the actual returned value on those platforms, or both?

Just in case:

- macOS: Displays `CFBundleDisplayName` if available, otherwise displays `CFBundleName`, otherwise is null.
- Windows: Displays the `productName` from the executable binary (no idea how that works)
- Linux: Similar implementation to web, displays the `app_name` from the `version.json`.

**Comment by Hixie** [comment]
Lack of documentation was my primary concern, it's hard for me to say if the returned value being different is a bug or not without knowing what the returned value is expected to be. :-)
