### ISSUE TITLE
[Question]: Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by abisao1** [fluttercommunity/plus_plugins#2948]
### What is your question?

Am getting this error after upgrading to the latest version: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'.
> error: invalid source release: 17

How do I go around this?

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by ckarmy** [comment]
Same error here 😭

**Comment by theolm** [comment]
Same here

**Comment by ChurikiTenna** [comment]
Same. 
But it's `Execution failed for task ':sensors_plus:compileReleaseJavaWithJavac'.` instead of package_info_plus in my case.

**Comment by mbfakourii** [comment]
> ~Same here~ Using java 17 solve it.

```dart
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
```

@theolm
Did it work with these settings?

**Comment by pouyamaroufi** [comment]
> > ~Same here~ Using java 17 solve it.
> 
> ```dart
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_17
>         targetCompatibility JavaVersion.VERSION_17
>     }
> 
>     kotlinOptions {
>         jvmTarget = '17'
>     }
> ```
> 
> @theolm Did it work with these settings?

Didn't work for me :(

**Comment by vbuberen** [comment]
<img width="509" alt="Screenshot 2024-05-19 at 13 33 45" src="https://github.com/fluttercommunity/plus_plugins/assets/13467769/5da3f9c4-e848-466d-a29c-ddaf1e0a05bb">
⬇️ 
<img width="856" alt="Screenshot 2024-05-19 at 13 33 52" src="https://github.com/fluttercommunity/plus_plugins/assets/13467769/a79fdca5-6e9e-41ae-8403-02f4bac12427">

Why claim something if you didn't do it in reality? Lying to other people doesn't really encourage to help you.
Plugin requires Java 17 as it is mentioned in the changelogs and since recently also in README.
you need to check that your IDE uses Java 17 for Android builds as it is suggested in the Stack Overflow post that is literally the first link in the Google search. 

https://stackoverflow.com/a/70215091/7339798

**Comment by theolm** [comment]
@mbfakourii I had to change my environment to use Java 17. I didn't touch the build Gradle.

I also had to change my CI to use Java 17.

**Comment by AhmedMahhmoud** [comment]
> @mbfakourii I had to change my environment to use Java 17. I didn't touch the build Gradle.
> 
> I also had to change my CI to use Java 17.

How did you manage to do that ? can you give me the steps

**Comment by mbfakourii** [comment]
> @mbfakourii I had to change my environment to use Java 17. I didn't touch the build Gradle.
> 
> I also had to change my CI to use Java 17.

How did you change the CI?
