### ISSUE TITLE
[Bug]: Missing WASM support

### ISSUE THREAD

**Issue by nietsmmar** [fluttercommunity/plus_plugins#3024]
### Platform

All

### Plugin

device_info_plus, package_info_plus

### Version

all

### Flutter SDK

all

### Steps to reproduce

run flutter build with `--wasm` flag.

I can't built my app for wasm because this package is not supporting it. As it is stable in flutter now, it would be nice if it is supported.

### Code Sample

```dart
flutter run web --wasm
```

### Logs

```shell
Context: The unavailable library 'dart:html' is imported through these packages:

    web_plugin_registrant.dart => package:device_info_plus => dart:html
    web_plugin_registrant.dart => package:package_info_plus => dart:html
```

### Flutter Doctor

```shell
irrelevant for this
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by vbuberen** [comment]
Mentioned packages added WASM support a few months ago already.
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/CHANGELOG.md#1010
https://github.com/fluttercommunity/plus_plugins/blob/main/packages/package_info_plus/package_info_plus/CHANGELOG.md#600

Please really use search instead of just marking the checkmark.
