### ISSUE TITLE
[Question]: how can I mock a connectivity change in unit tests? 

### ISSUE THREAD

**Issue by cestaxelle** [fluttercommunity/plus_plugins#3029]
### What is your question?

Hi,
We've been using ConnectivityPlus for a while and it works like a charm, but I can't figure out how to mock a connectivity change in a unit test. 
I do have a mock instance of Connectivity (built with Mockito), and I've tried stubbing the method (`when(mockConnectivity.onConnectivityChanged).thenAnswer((_) => Stream<List<ConnectivityResult>>.fromIterable([[ConnectivityResult.none],]));`) but it obviously doesn't trigger a call to `onConnectivityChanged`. I've also tried using `checkConnectivity()`, thinking that if it returns a different value from previously, `onConnectivityChanged` would be called, but it doesn't seem to work.
Is there any way to trigger a call to `onConnectivityChanged` without having to mock the whole Platform?
Many thanks!

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Personally, I'd not attempt to mock the plugin directly (or any 3rd party code for what is worth), but rather wrap it in my own class, so I can inject a fake/mock in code when needed.

Then, this is more a question on how to mock a `Stream` rather than a plugin question, I'd recommend you to ask on Stack Overflow, as more people will see it and may be able to help.

Probably, you want to set `onConnectivityChanged` to your own `StreamController` which you can emit values to it, and will be received by the listeners.

Something like (typed from memory, not actual working code)

```dart
when(mockConnectivity.onConnectivityChanged).thenReturn(myStreamController.stream);

// later in code:

myStreamController.add([ConnectivityResult.none]);
```

As mentioned, I'll recommend you to look up how to mock a Stream on Stack Overflow or similar sites, so closing this ticket for now.
