### ISSUE TITLE
[Bug]: Version Conflict with get Package due to web Dependency

### ISSUE THREAD

**Issue by fisforfaheem** [fluttercommunity/plus_plugins#3181]
### Platform

android 13

### Plugin

share_plus

### Version

latest

### Flutter SDK

3.22

### Steps to reproduce

Create a new Flutter project.
Add get: ^5.0.0-release-candidate-6 and share_plus: ^10.0.1 to the pubspec.yaml.
Run flutter pub get.
The dependency resolution fails due to a conflict between the web versions required by get and share_plus.

### Code Sample

```dart
dependencies:
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-6
  share_plus: ^10.0.1
```

### Logs

```shell
Because share_plus >=10.0.1 depends on web ^1.0.0 and get 5.0.0-release-candidate-6 depends on web >=0.4.0 <0.6.0, share_plus >=10.0.1 is incompatible with get 5.0.0-release-candidate-6.
And because no versions of get match >5.0.0-release-candidate-6 <6.0.0, share_plus >=10.0.1 is incompatible with get ^5.0.0-release-candidate-6.
So, because my_app depends on both get ^5.0.0-release-candidate-6 and share_plus ^10.0.1, version solving failed.
```

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 3.22.0, on macOS 12.3, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
```

### Checklist before submitting a bug

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I'm using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
Version conflicts are not bugs. Either ask the devs of "get" to upgrade the web dependency or use a earlier version of share_plus.

**Comment by fisforfaheem** [comment]
Why  is share_plus using old dependencies?

**Comment by miquelbeltran** [comment]
`share_plus` uses `web ^1.0.0`. `get` is using `web >=0.4.0 <0.6.0`

`get` is using an old and incompatible version of `web`, you should ask them to upgrade to `1.0.0`, use an old version of `share_plus` or do a dependency overrides.

**Comment by vbuberen** [comment]
It is not the first time this person comes with such dependency resolution issues.

I would advise to read the official documentation and learn how to manage such situation instead of coming back with issues every few releases when some package haven't updated dependencies yet.
https://docs.flutter.dev/packages-and-plugins/using-packages#conflict-resolution

**Comment by fisforfaheem** [comment]
> `share_plus` uses `web ^1.0.0`. `get` is using `web >=0.4.0 <0.6.0`
> 
> `get` is using an old and incompatible version of `web`, you should ask them to upgrade to `1.0.0`, use an old version of `share_plus` or do a dependency overrides.

They updated, but now Flutterfire is sing old dependencies :( such a pain

**Comment by fisforfaheem** [comment]
> It is not the first time this person comes with such dependency resolution issues.
> 
> I would advise to read the official documentation and learn how to manage such situation instead of coming back with issues every few releases when some package haven't updated dependencies yet. https://docs.flutter.dev/packages-and-plugins/using-packages#conflict-resolution

This can be fixed if you people also make a beta version

**Comment by vbuberen** [comment]
> This can be fixed if you people also make a beta version

With a few similar issues and comments like https://github.com/fluttercommunity/plus_plugins/issues/3181#issuecomment-2291620125 you clearly showed that you don't fully understand the topic of dependencies versioning and how to resolve possible versioning issues.

So suggesting somebody to do more work to maintain free packages instead of trying to learn how to deal with versioning is not the best way. I would gladly do betas if it was a commercial product and people would actually pay instead of giving advises.

**Comment by fisforfaheem** [comment]
I agree with you. Kindly add a donation button please
