### ISSUE TITLE
android_alarm_manager_plus - function periodic not working

### ISSUE THREAD

**Issue by jeihcio** [fluttercommunity/plus_plugins#323]
I'm using the 'plus_plugins' example itself and the periodic method is not firing, the oneShot method works perfectly. Periodic is not triggering the callback function. I believe it's some mistake of mine, could you guide me? I've already tried to find the solution elsewhere

**Comment by Chinmay-KB** [comment]
What was the interval you had passed for periodic triggering?
If you have tried just changing `oneShot` to `periodic` in the example code, the callback will fire, but not at the desired time. Since Android 5.1, the minimum interval for a periodic fire using AlarmManager is 1 minute.  So even if you pass a smaller duration, it will default to 1 minute. If you want to call more frequently, you should look into [Handler](https://developer.android.com/reference/android/os/Handler).

**Comment by jeihcio** [comment]
I tested several minutes for the periodic, including 15 and 30 minutes

**Comment by Chinmay-KB** [comment]
Could you provide a code sample in which the issue can be reproduced? Also the AndroidManifest.xml. I have tried it with the example code and it worked fine on my device.

**Comment by jeihcio** [comment]
I got it here, but I had to add some code in "app/build.gradle".

implementation "com.android.support:multidex:2.0.1"

I can't explain why it worked, but it worked.

thanks!

**Comment by baguio** [comment]
Not even sure this is related, but mine worked too after updating multidex. Was using 1.0.2 before this

**Comment by Chinmay-KB** [comment]
There's an error which says number of method references in a dex file cannot exceed 64k references. That's where multidex helps. Not sure but maybe that was the issue. But as far as I know the app should not have built in the first place if this was the error 🤔

**Comment by jeihcio** [comment]
After that it started working for me, however, now I'm thinking it was just cohesiveness, because then it stopped working, then I went to look on my cell phone and turned off the battery saving restrictions (my cell phone is xiaomi) and it started working again. I believe that the real problem must be this one of restriction
