### ISSUE TITLE
[Question]: Call for upgrading to support latest Flutter 3.323.3 by supporting latest gradle and java android studio

### ISSUE THREAD

**Issue by faheemstepsharp** [fluttercommunity/plus_plugins#3305]
### What is your question?

Can all the packages upgrade to Fully support Flutter 3.23.3 and move to latest java and gradle? this will make them stabler, This will be very helpful

### Checklist before submitting a question

- [X] I searched issues in this repository and couldn't find such bug/problem
- [X] I Google'd a solution and I couldn't find it
- [X] I searched on StackOverflow for a solution and I couldn't find it
- [X] I read the README.md file of the plugin
- [X] I am using the latest version of the plugin
- [X] All dependencies are up to date with `flutter pub upgrade`
- [X] I did a `flutter clean`
- [X] I tried running the example project

**Comment by miquelbeltran** [comment]
> and move to latest java and gradle?

It is the other way around, because the plugins use java that is further than what is shipped with Flutter projects by default, that causes compilation issues unless devs upgrade their projects.

The plugins from the Flutter team have set source compatibility to Java 11 (and that change only came up 2 days ago: https://github.com/flutter/packages/pull/7795), while ours are at Java 17.
