### ISSUE TITLE
[android_intent_plus] Possibility to get results from an intent

### ISSUE THREAD

**Issue by Kerenok** [fluttercommunity/plus_plugins#344]
Scanning the code and the example, it seems that getting results from an intent is not currently supported (for example result from a SCAN action for a barcode scanner intent). 

Is it possible to extend the plugin in a Flutter application to use invokeMethods on _channel and get back some data?

**Comment by mhadaily** [comment]
@miquelbeltran can you advise here?

**Comment by miquelbeltran** [comment]
The plugin does not support this functionality. The way the plugin works would need to be changed considerably to use `startActivityForResult` instead of `startActivity` and capture and return results, similarly to what the `image_picker` does.

**Comment by Kerenok** [comment]
Thanks for the response. I'll check the image_picker code.

**Comment by varunbhalerao56** [comment]
Hey, any updates on this? I am opening another app where the user needs to press login to verify their identity (using government API). Once the user presses login it returns me back to my app. The problem is that once the user has pressed login a link should be generated but I am not able to capture the link with the auth token.

**Comment by miquelbeltran** [comment]
You will have to implement this by yourself, it is not the intended functionality of the plugin.
