### ISSUE TITLE
identifierForVendor change when remove and then reinstall app

### ISSUE THREAD

**Issue by quachanhdung** [fluttercommunity/plus_plugins#452]
## System info

Issue occurs on: iOS / Android / both
Plugin name:
Plugin version:
Flutter doctor output:

```
paste it here...
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by mhadaily** [comment]
@quachanhdung can you elaborate more? and add step to reproduce?

**Comment by Leffe108** [comment]
Looks like a duplicate of https://github.com/fluttercommunity/plus_plugins/issues/447

[Apple docs](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) says that this is expected behaviour. (unless you publish more than one app, then it resets when users has removed all your published apps)

**Comment by mhadaily** [comment]
a duplicate of https://github.com/fluttercommunity/plus_plugins/issues/447
