### ISSUE TITLE
Return Human Readable Name of the device (Commercial name)

### ISSUE THREAD

**Issue by venzeo** [fluttercommunity/plus_plugins#560]
## Use case
Users are confused it they see name of their device is "iPhone 14,5" or "Samsung SM-G991".

## Proposal
Instead of 

- iPhone 14,5 we can show human readable name: "iPhone 13"
- Samsung SM-G991 we can get "Samsung S21"

Plugin should still return iPhone 14,5 to not create any compatibility issues. But new parameter would be great to add "commercialName" or something similar...

**DATABASES:**

- iOS models: https://gist.github.com/adamawolf/3048717
- Android models: ???

**Comment by venzeo** [comment]
Maybe it can be an additional optional extension of this library, something what extends the plugin and includes either iOS library or Android Library. So only people who needs it would extend it to save storage within the app.

**Comment by Boehrsi** [comment]
I really like this idea, as it combines the best of the online and offline approach. But I wouldn’t implement a native iOS / Android part, I would provide just one additional extension library. This library then contains the new call for all platforms and the lookup data (everything handled on the Dart layer, without other native calls than performed by the “normal” device_info_plus plugin). 
I wouldn’t use an extra native layer for every platform because of the overhead for updates / releases and so on. I also think that the amount of storage required for the actual lookup data could be reduced to be “okay to use”.

**Proposal:**

- device_info_plus_extended will be created
- The new plugin will depend on the normal  device_info_plus plugin
- The new plugin contains all lookup data and the new call
- The lookup data will be created by a script (I already thought about a neat Dart script to fetch and convert the data) to directly provide a simple Dart map or something fitting. So we have no need to convert JSON or something similar back and forth. I will try to make everything as lazy as possible to avoid unnecessary memory consumption

Doing this we can update the lookup data independently from the actual plugin, we have always fast lookups. Later we could also add eg. Macs lookups.
The only downside would be the overhead here in the repository. But I would keep everything in line with the current setup (Melos and so on).

@mhadaily would this be a feasible solution or do you think this would be to much?

@mhadaily the on

**Comment by venzeo** [comment]
I just checked the size of all Android devices in zipped format 341Kb, unzipped 2.6MB.
@Boehrsi we like your proposal.

**Comment by mhadaily** [comment]
Thanks for your effort, @Boehrsi  this is creat add-on, although I think this should somehow be the dev's responsibility in their application to take care of the human readability of the device.

Since you have done a great job so far, let's discuss this with other core team members to see which option is better.

I think it's ok to add this to our main package; I am not sure if we want another package to maintain. What do you think about this issue and PR @jpnurmi and @miquelbeltran ?

**Comment by Boehrsi** [comment]
No problem I'm happy to help this project as nearly all my own apps depend on at least one *_plus package. I'm open for all possible solutions. Even if decision is to not add it to the device_info_plus package nor to create e.g. device_info_plus_extended, I would at least create a package on my own, so devs who need such a feature could use it. But I would think this would be a helpful addition for device_info_plus. 
For reference here is the script (https://github.com/Boehrsi/device_identifiers) which fetches the data and would serve as source. The there created lookup file could be integrated / updated regularly in the actual dev facing package.

**Comment by miquelbeltran** [comment]
> I think this should somehow be the dev's responsibility in their application to take care of the human readability of the device.

I agree with that. I think this functionality should be delivered in an independent plugin (that uses device_info as dependency).

**Comment by Boehrsi** [comment]
> I agree with that. I think this functionality should be delivered in an independent plugin (that uses device_info as dependency).

@miquelbeltran Thanks for the input. Would "independent plugin" for you mean within the `plus_plugins` world or one I publish separately by myself?

**Comment by miquelbeltran** [comment]
Outside of the plus_plugins repo, because it is already unmanageable for us the amount of plugins in this repo. But you could talk to people on the 'fluttercommunity' see if they want to host the plugin on their github organization.

**Comment by Boehrsi** [comment]
Thanks for clarification. I already thought so and this is totally understandable. Wouldn't be a problem for me to publish it myself, but having a further look around could also be an idea. Thanks for the input.

I would suggest I just prepare the repo & plugin release own my own right now, so the actual functionality will be available and @venzeo and others can use it. This way we didn't overload the `plus_plugins` even more and we still keep everything modular. As soon as everything is ready (probably today or tomorrow) I would link everything here and we could close this issue. Would this be a feasible solution for everybody involved?

**Comment by Boehrsi** [comment]
Here we go https://pub.dev/packages/device_marketing_names the package is released in a first version. I'm currently adjusting some small stuff / the pub.dev score and similar stuff, but in general it's ready to use. Therefore and if this is okay for @venzeo I think this issue can be closed.

**Comment by venzeo** [comment]
@Boehrsi superb! you rock! thank you so much on behalf of all flutter developers and open source world.

**Comment by miquelbeltran** [comment]
Thank you @Boehrsi for all the work!

**Comment by Boehrsi** [comment]
@venzeo @miquelbeltran thanks for the super positive words, this really levels up my open source motivation.
