### ISSUE TITLE
Conflicts between connectivity_plus and Reachability on iOS

### ISSUE THREAD

**Issue by tengyeekong** [fluttercommunity/plus_plugins#563]
## System info

Issue occurs on: iOS
Plugin name: connectivity_plus
Plugin version: ^2.0.2

## Steps to Reproduce

App launched and stuck at splash screen.

## Logs

<img width="607" alt="Screenshot 2021-10-14 at 3 48 39 PM" src="https://user-images.githubusercontent.com/19898540/137274253-158dfd28-74b3-4a73-83b3-33f56178cb15.png">

<img width="779" alt="Screenshot 2021-10-14 at 3 47 29 PM" src="https://user-images.githubusercontent.com/19898540/137274059-152d7ae4-1769-44e6-8fc1-aea0ac290f10.png">

**Comment by fdastgir** [comment]
Getting same issue

**Comment by tengyeekong** [comment]
> I've just checked `connectivity_plus` example on both simulator and iPhone and I cannot reproduce your issue. Please create the following app and post your results.
> 
> ```
> $ flutter create --platforms ios demo
> $ cd demo
> $ flutter pub add connectivity_plus
> ```
> 
> ```dart
> import 'package:connectivity_plus/connectivity_plus.dart';
> import 'package:flutter/material.dart';
> 
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   final connectivity = await Connectivity().checkConnectivity();
> 
>   runApp(MyApp(connectivity: connectivity));
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({
>     Key? key,
>     required this.connectivity,
>   }) : super(key: key);
> 
>   final ConnectivityResult connectivity;
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         body: Center(
>           child: Text('$connectivity'),
>         ),
>       ),
>     );
>   }
> }
> ```

Same result.
If run from Android Studio then the app closed after the splash screen, no error in the log.
If run from Xcode then the app stuck at the splash screen and show "Symbol not found: _OBJC_CLASS_$_Reachability" error in Xcode log.
This issue should be causing by using different Reachability classes. "connectivity_plus" using Reachability, and the native iOS using ReachabilitySwift.

**Comment by miquelbeltran** [comment]
Weird enough, I also got this error today for a project that simply worked like a week ago. Similar issue as reported originally, same error, clean didn't do anything.

Error:
```
(lldb) dyld[11380]: Symbol not found: _OBJC_CLASS_$_Reachability
  Referenced from: /private/var/containers/Bundle/Application/DE61E60B-1A26-430B-9991-50B615F82B6E/Runner.app/Frameworks/connectivity_plus.framework/connectivity_plus
  Expected in: /private/var/containers/Bundle/Application/DE61E60B-1A26-430B-9991-50B615F82B6E/Runner.app/Frameworks/Reachability.framework/Reachability
```

the used version of `connectivity_plus` is 1.4.0, because it is a dependency from another package.

Relevant part of my doctor:

```
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-DE)
    • Flutter version 2.5.3 at /Users/miquel/dev/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

The minimal example from @alexbatalov worked for me so I could not reproduce the issue there.

I also tried to override the dependency to 2.0.3, but the same issue stays.

Running with `--verbose` didn't give me any relevant info besides what has been already been reported.

**Comment by miquelbeltran** [comment]
I think I got a solution.

The problem is when you have both the cocoa pods Reachability and ReachabilitySwift in the same project.

In my case I was suing PusherSwift v8.0.0 which depends on ReachabilitySwift 5.0, this causes a problem with connectivitu_plus which uses Reachability 3.2.

Thankfuly PusherSwift no longer uses ReachabilitySwift so this issue is now gone for me.

Since Reachability is the official framework and ReachabilitySwift is a thrid party framework, and ReachabilitySwift doesn't seem to be maintained anymore (see https://github.com/ashleymills/Reachability.swift/issues/385 for example) I am inclined to say that the issue is not on our side but on the devs using ReachabilitySwift.

**Comment by miquelbeltran** [comment]
hey all, I was able to migrate the iOS plugin from Reachability to ReachabilitySwift, which got rid of the incompatibilities with other plugins. We also have now a shinny swift implementation (shamelessly stolen from the MacOS implementation). I tested this on my project and the solution works.

You can try the version 2.1.0 or just grab it with flutter pub upgrade.

**Comment by StasKalishenko** [comment]
But what to do with this problem if your other plugins or native code uses Objective-C implementation of Reachability? Objective-C and Swift implementations can't work together at the same time and project is broken until removing one of them. Migrating to Swift variant of Reachability you are braking compatibility with other stuff.

**Comment by miquelbeltran** [comment]
> But what to do with this problem if your other plugins or native code uses Objective-C implementation of Reachability?

You will have to migrate them or use an old version of this plugin.

**Comment by fengkaijia** [comment]
> > But what to do with this problem if your other plugins or native code uses Objective-C implementation of Reachability?
> 
> You will have to migrate them or use an old version of this plugin.

That really does not sound like a good idea since half of the project relying on this library will need to freeze on a legacy version. Maybe remove Reachability.swift at all, similar to what this project did: https://github.com/snowplow/snowplow-objc-tracker/issues/437#issuecomment-565455505

**Comment by kapil708** [comment]
I solved it check the link.
https://stackoverflow.com/a/78105848/5374771

**Comment by latifmge** [comment]
thats because connectivity_plus.
i read at [](https://pub.dev/packages/connectivity_plus/changelog) 
in version 6.0.2, i think they fix it.
6.0.2
REFACTOR(connectivity_plus): remove ReachabilityConnectivityProvider and ReachabilitySwift dependency ([#2813](https://github.com/fluttercommunity/plus_plugins/issues/2813)). ([f9ad927f](https://github.com/fluttercommunity/plus_plugins/commit/f9ad927f5c18f8ed8d4c22a24476430239c13492))
