### ISSUE TITLE
Open vcf file with Intent

### ISSUE THREAD

**Issue by Somtobro** [fluttercommunity/plus_plugins#611]
The examples you guys gave are poor, very poor...how to open a vcf file from storage??... I'm trying to open a vcf file in storage so I can import it

**Comment by harriseldon** [comment]
Can you elaborate on which examples you think need improving? What were you expecting to see that you did not?
Can you also explain your use case in more detail? It seems like you want to register a url handler that listens to vcf:// urls so that when a user selects share on a vcf, your application is one of the choices.

**Comment by harriseldon** [comment]
I still do not understand your use case, but here is an example of opening an existing vcf file on your phone and sharing it via share plus.
https://dartpad.dev/?d33fe84e36e1c0b924ab2abcface8fe4

It uses the share_plus library to share files and file_picker to pick a file. VCard files have mime type text/vcard or text/directory. It appears that iOS treats all non-mages as text files. For Android, I was able to attach the vcard to any application including email.

**Comment by Somtobro** [comment]
Sorry I'm just replying now
I don't know how I missed
I still need this....and the link you sent is an empty dart pad

Use case:I was trying to open and automatically import a vcf file from my
flutter app by clicking on a button because that's what happens when u
click on a vcf file
