### ISSUE TITLE
[share_plus] How to handle device rotation? (iPad)

### ISSUE THREAD

**Issue by saibotma** [fluttercommunity/plus_plugins#636]
Currently, the share sheet keeps its origin where it was set using the `sharePositionOrigin` parameter, when the device gets rotated. However, this position is wrong in most cases after a rotation, as it often is the position of a button on screen, which will have a different position when rotated.

Is there a way to update the position after rotation?

**Comment by saibotma** [comment]
This is not stale.

**Comment by saibotma** [comment]
This is not stale and also not completed.

**Comment by miquelbeltran** [comment]
> Is there a way to update the position after rotation?

How is this that handled natively on Swift/Objective-C?

**Comment by saibotma** [comment]
Will take a look at this and comment on this issue. The issue ist not stale.

**Comment by saibotma** [comment]
On native iOS, the share sheet gets closed and then reopened at the new position after rotation.

https://github.com/fluttercommunity/plus_plugins/assets/26022902/84bf18ee-37c7-40d2-889f-00aa11ef41e5

However, I still have not figured out whether this gets done automatically or if developer have to do this on their own.
One could replicate the behaviour using `share_plus` if `share_plus` would allow an already opened share sheet.

**Comment by saibotma** [comment]
**Note**
There are multiple options to set the anchor point.
As stated [here](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller#1653440), those are:
- Using a `sourceItem`: This might provide the autorotation functionality (did not test), however can not be used with Flutter, obviously.
- Using a combination of `sourceView` and `sourceRect`: Currently used for share plus.

**Comment by ivannatividad** [comment]
Hi, I’m currently experiencing the same issue and noticed that this been open for quite a while without any recent updates. Just checking in to see if there’s been any progress on this? 

@saibotma were you able to find any workarounds? 😅 Thanks

**Comment by saibotma** [comment]
@ivannatividad Have no workaround.

**Comment by roth-arasys** [comment]
Still reproducible on iPadOS 26.5 with share_plus 13.3.0, and not limited to rotation: resizing the app window while the share sheet is open leaves the popover behind. I spent some time measuring what UIKit actually offers here, because it turns out the interesting question is not *how* to reposition the popover but *who knows where the trigger went*.

## Why the current code cannot follow

`sharePositionOrigin` is a one-shot value: `MethodChannelShare._toPlatformMap` copies it into `originX/originY/originWidth/originHeight`, `FPPSharePlusPlugin` assigns it once to `popover.sourceRect`, and `share()` returns only after dismissal. Nothing on the Dart side can revise it in between.

## What UIKit offers (measured on an iPad Air 13-inch M4 simulator, iPadOS 26.5)

**[`willRepositionPopoverTo`](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontrollerdelegate/popoverpresentationcontroller(_:willrepositionpopoverto:in:)) fires reliably.** With a delegate attached, UIKit called it 575 times during a single window drag. The rect it proposes is always the original one, never recomputed, but writing a new value into the pointer moves the popover and the value is retained:

```
willRepositionPopoverTo #2 proposed={{682, 511}, {2, 2}}   // original rect
overrode rect to {{120, 120}, {2, 2}}
willRepositionPopoverTo #3 proposed={{120, 120}, {2, 2}}   // override retained
```

**Anchoring to a view works without a delegate at all.** `UIView` is a conforming type of [`UIPopoverPresentationControllerSourceItem`](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontrollersourceitem); with [`popover.sourceItem`](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller/sourceitem) set to a view held in place by constraints, the popover stayed attached to it across the whole resize:

```
presenting via sourceItem, anchor={{1290, 948}, {44, 44}} bounds={{0, 0}, {1366, 1024}}
reposition #100 proposed={{inf, inf}, {0, 0}} anchor={{707, 764}, {44, 44}}
reposition #700 proposed={{inf, inf}, {0, 0}} anchor={{1004, 737}, {44, 44}}
```

Two side notes: with `sourceItem` set, the delegate's proposed rect is `{{inf, inf}, {0, 0}}` and must not be used. And implementing the protocol on a custom class does not compile (`Type 'X' does not conform to protocol 'UIPopoverPresentationControllerSourceItem'`) even with `frame(in:)` implemented, so a plugin-owned item that computes the rect on demand is not an option.

## Why that is not enough on its own

I built the plugin-side half of this — an invisible anchor view at `sharePositionOrigin`, handed to `sourceItem`, removed again in `completionWithItemsHandler`: [fix/ipad-popover-anchor](https://github.com/roth-arasys/plus_plugins/tree/fix/ipad-popover-anchor). It works, and the popover follows a resize.

But the anchor has to be *held somewhere*, and the plugin does not know where the Flutter widget went. I tried two ways of holding it, in an app whose trigger is a floating action button:

- Pinning the anchor's centre proportionally to the view. The popover followed, but loosely — while dragging, it kept switching between sitting left of the button and above it, and the arrow met the button at varying heights.
- Pinning it to the nearest edges with the offset it had when the sheet opened. This tracked the button well and stayed on it across repeated resizes, with a stable arrow direction.

The second one is only right because a floating action button keeps a fixed distance to the corner. It is measured against the safe area while the anchor is pinned to the view bounds, so the two diverge as soon as the insets change, and a widget laid out proportionally or inside a scrollable is not tracked at all.

So any plugin-only fix is a guess about the host app's layout. That is why I am not opening it as a PR.

## Proposal

Let Dart supply the position while the sheet is open, and let UIKit do the repositioning:

1. **`share_plus_platform_interface`**: a method to update the origin of a sheet that is currently presented, e.g. `updateSharePositionOrigin(Rect origin)`. No change to `ShareParams`.
2. **iOS**: keep an anchor view for the presented sheet and set its frame from that call. `sourceItem` already makes UIKit follow it, so no delegate and no repositioning logic in the plugin.
3. **App side**: re-measure in `WidgetsBindingObserver.didChangeMetrics` and push the new rect. This is a handful of lines and could go in the README rather than being mandatory — without it, behaviour is exactly as today.

A pull-based variant, where the plugin asks Dart for the rect when UIKit repositions, would be nicer for users but does not fit: `willRepositionPopoverTo` is synchronous and platform channels are not.

Two questions before I write any of it:

- Is an iOS/macOS-only method on the platform interface acceptable here? `sharePositionOrigin` has the same scope, but CONTRIBUTING rules out single-platform *features*, and I would rather ask than guess.
- Would you prefer the anchor-view change on its own first, as a strict improvement over a fixed rect, even though it stays approximate?

**Environment:** share_plus 13.3.0, share_plus_platform_interface 7.2.0, iPad Air 13-inch (M4) simulator, iPadOS 26.5, single `FlutterView`, trigger is a `FloatingActionButton`.
