### ISSUE TITLE
[device_info_plus] androidInfo.isPhysicalDevice becomes nullable

### ISSUE THREAD

**Issue by xmany** [fluttercommunity/plus_plugins#706]
Hi guys, I am trying to switch from `device_info` to `device_info_plus`, and I noticed that the property `isPhysicalDevice` for `DeviceInfoPlugin.androidInfo` becomes nullable;

The document does not say how to treat the null value, should I consider the null value as physical device or not? or is there other function I should call first, to help stabilise this property?

Really appreciate it if someone can clarify, thanks!

**Comment by vbuberen** [comment]
Hello. I had a brief look at the code and I think that there should be no cases when it is `null`.
I would suggest to treat `null` as not a physical device, since you receive no explicit `true` there. 

I will take a look if we can improve this part for Android as I am currently migrating all plugins to Kotlin and do some small fixes along the way. `device_info_plus` is still in the queue for me.

**Comment by xmany** [comment]
> Hello. I had a brief look at the code and I think that there should be no cases when it is `null`. I would suggest to treat `null` as not a physical device, since you receive no explicit `true` there.
> 
> I will take a look if we can improve this part for Android as I am currently migrating all plugins to Kotlin and do some small fixes along the way. `device_info_plus` is still in the queue for me.

Thanks! helps a lot!

**Comment by vbuberen** [comment]
I think we need to take a look at it again as I still haven't migrated the `device_info_plus` to Kotlin.

**Comment by vbuberen** [comment]
Closing as resolved by #1246
