### ISSUE TITLE
[share_plus] Preserve original file names when sharing images on iOS

### ISSUE THREAD

**Issue by liri2006** [fluttercommunity/plus_plugins#821]
## Use case

Currently, when using "Save to files" while sharing images, saved files would have new generic names like "image PNG", "image PNG 2", etc, instead of ones they were shared with.

This is the case on iOS only and only when sharing images.

The problem seems to be here:
![image](https://user-images.githubusercontent.com/2411723/161416583-19ea6623-0aee-4b23-82d7-a3c6a33d92f2.png)

If images are shared as NSURL instead of as UIImage, then system preserves original file names.

## Proposal

Maybe it is possible to add some kind of a flag like "shareImagesAsFiles" or some other way to force sharing images as NSURL.

**Comment by Coronon** [comment]
Can you broaden the scope so that we can close #808 in favour of this one? :)

I'll have a look into this when I have time on my hands.

**Comment by liri2006** [comment]
@Coronon I've edited the title and description, let me know if that is ok.

**Comment by Coronon** [comment]
I think I found an interesting fix - remove the current separation between images and other files, as iOS automatically detects images.

We also get the added benefit of a real share preview (before it was just your App's icon).

I am just wondering why this was included in the first place, maybe old iOS versions handle images differently? @miquelbeltran do you know anything about this?

![image](https://user-images.githubusercontent.com/33808743/163690688-fd5af79b-5d72-4cc9-ae51-532f55b6f1a8.png)
![image](https://user-images.githubusercontent.com/33808743/163690695-8f4a7f92-d995-4439-8f47-9fe05eb90a82.jpeg)

**Comment by Coronon** [comment]
Ok, I was able to implement the little description myself, we get `JPEG • 354 KB` instead of `JPEG Image • 354 KB` - but that should be fine. If it is really important to people I can implement some kind of lookup table for different mime types. No file extensions are also correctly handled.

We could consider allowing people to write their own description, but that would probably be an Apple only feature again - it's hard to provide features when you are bound to so many platforms...

![image](https://user-images.githubusercontent.com/33808743/163695502-2b7f9533-5c9a-4393-a6d8-91e3a168ccf8.png)

**Comment by Coronon** [comment]
As always I provide a test respository for these changes [here](https://github.com/Coronon/share_plus_example).

I will create a PR soon if no one faces issues - would love everyone to try out the changes :)
