### ISSUE TITLE
MagnetometerEvent to compass values

### ISSUE THREAD

**Issue by JoergPf** [fluttercommunity/plus_plugins#903]
Hi, 
I'm desperately searching for an example on how to get the 0-360 compass values out of the MagnetometerEvent. Any hint is very appreciated. 
Thanks Joerg

**Comment by Mukund-Tandon** [comment]
We can do this-
```
magnetometerEvents.listen((MagnetometerEvent event) 
{
      double D = 360 - atan2(event.x, event.y) * (180 / pi);
      if (D < 0) {
        D += 360;
      }
      print(D);
    });
  }
```

For reference - https://arduino.stackexchange.com/questions/18625/converting-three-axis-magnetometer-to-degrees

You can also use this package - https://pub.dev/packages/flutter_compass

**Comment by ben-xD** [comment]
The code snippet in https://github.com/fluttercommunity/plus_plugins/issues/903#issuecomment-1158424761 is wrong. I've tried it and gave 400+ degrees.

I would highly recommend using https://pub.dev/packages/flutter_compass or writing your own plugin instead of using the magnetometer readings (unit: micro Teslas), because these packages use the operating-system calculated heading, which could use multiple sensors (sensor fusion) to give improved accuracy based on the hardware, as well as compensate for the location (geomagnetic pole is not the same as magnetic pole).
