### ISSUE TITLE
[Request]: share image or file from uint8list

### ISSUE THREAD

**Issue by ARASHz4** [fluttercommunity/plus_plugins#933]
### Plugin

share_plus

### Use case

Share image or file from uint8list

### Proposal

I want to share image or file from uint8list, but only can share file from path

**Comment by Coronon** [comment]
Hi there, we need to pass the OS paths on the plugin side, which is why we only accept paths on the dart side.

Is it unfeasible to write your bytes to a file and then passing that file to `share_plus` in your codebase? I think the only way we could implement this is writing the file to disk ourselves, which would just add extra complexity for no real gain.

PS: You could just create a temporary directory or use the temp dir `path_provider` offers.

Looking forward to hearing from you :)

**Comment by PhamNgocPhi** [comment]
Hi there, I use Share_Plus to share the file on the web. The requirement is to get data on the screen, write them to a file, and share them. But I can't create a temporary file like mobile on the web. So is any way to do this? or do you have any suggestions?
Thanks and have a nice day!

**Comment by Jamalianpour** [comment]
I want to share image from uint8list and use [wc_flutter_share](https://pub.dev/packages/wc_flutter_share) and It's work.
But now it was DISCONTINUED

**Comment by miquelbeltran** [comment]
Have you tried to store the file in a tempor path and then share that file?

**Comment by Gitzzq** [comment]
Hi,

I encountered the same problem, for security concern I cannot allow the app to write the data from Uint8List to a temporary file.  It would be great if can make this package to share data without using a temporary file.

Thanks.

**Comment by miquelbeltran** [comment]
Nope, that's impossible, you cannot share a binary payload via share intents.

Maybe you want to try to upload the file to your own servers and then sharing the URL.

Closing this issue as the original has been resolved, as the plugin supports sharing `XFile` created from data.
