### ISSUE TITLE
[Request]: Please add barometer

### ISSUE THREAD

**Issue by vitalsh** [fluttercommunity/plus_plugins#955]
### Plugin

sensors_plus

### Use case

I want to make a cross-platform baro altimeter feature in the app I'm building (for gliding)

### Proposal

 Barometric readings: hectopascals and altitude

**Comment by aanas-sayed** [comment]
Is there anyone working on this? I can try and push and update for the barometer on Android but as I understand unless all platforms are supported its unlikely to be accepted?

**Comment by miquelbeltran** [comment]
That's correct, we don't accept new feature implementations if they only cover one platform in order to avoid feature fragmentation: https://github.com/fluttercommunity/plus_plugins/blob/main/CONTRIBUTING.md#-cannot-be-accepted

Nevertheless, there are several barometer plugins already: https://pub.dev/packages?q=barometer

**Comment by aanas-sayed** [comment]
Thanks @miquelbeltran for clarifying. I have implemented it on all platforms now. I understand other plugins exist but there's none that are properly maintained. There's also none that integrate motion related sensors with altitude.

**Comment by aanas-sayed** [comment]
Can this be closed now?

**Comment by miquelbeltran** [comment]
Should have been closed when the PR was merged, indeed.
