### ISSUE TITLE
[Request]: Please add support to send emails.

### ISSUE THREAD

**Issue by FluffyBunniesTasteTheBest** [fluttercommunity/plus_plugins#967]
### Plugin

shapre_plus

### Use case

The app contains a "Contact Support" button to help the user getting help quickly. When pushing it, an email is created that:

1. Has the recipient address and subject already set.
2. Shows various platform and device related information at the message body.
3. Contains the apps configuration as an attachment.
4. Contains app related data in a second attachment.

In case of an problem, the only thing the user has to do is to briefly state the problem and hit the send button.

### Proposal

It would be very useful if:

1. The platforms share UI could be filtered to show email clients only.
2. An email client could be opened showing a new message with subject, recipient, message body and attachments already populated.

**Comment by miquelbeltran** [comment]
This would probably make more sense as separated plug-in that uses platform APIs to send emails. E.g. with an Android Intent.

**Comment by vbuberen** [comment]
I agree here that it should be a separate plugin, not part of Plus_plugins. I needed to do something similar to the original request a year ago and can say that it is quite painful, considering that not all email clients follow the specs of provided data, so for some email apps you still end up with just an empty compose view opened or just on the main screen of such email client. In the end client just gave up on covering all email client apps, especially those from different German services. 
Not to mention that on iOS it is also quite bad, because not all email app clients provide their launch schemas, as well you can't fine them in the internet, so you can't really open such clients.

P.S. It seems that there is already a plugin with such functionality that author of the issue needs: https://pub.dev/packages/flutter_email_sender

Based on availability of another plugin closing this issue.
