### ISSUE TITLE
[Request]: Should add Android id again

### ISSUE THREAD

**Issue by IMWaqasFarooq** [fluttercommunity/plus_plugins#972]
### Plugin

device_info_plus

### Use case

we need android id to keep records of the device, in an earlier version of your package it's there, but now you remove it by saying to avoid violating the google play policiy.
I didn't understand hows it is a violation of google play policies, I am aware that google updated their policies, but it is for applications when we upload it on the play store, and there we have to give a reason why we are getting Android id and then google allow us for it, I am doing this for my native application. hows it links with your library?

### Proposal

Please update your library and add this feature again it's much a needed feature for developers. , because google play policies violation is for developers who are uploading their application on the play store and not telling them a valid reason for it

**Comment by javaherisaber** [comment]
@IMWaqasFarooq 
I couldn't find any indication of policy related subject regarding Android-ID in Google play's policy updates
https://support.google.com/googleplay/android-developer/answer/11995078#user_data_preview

Can you send me a link to your reference on this policy violation?

**Comment by ksheremet** [comment]
@javaherisaber 
> Can you send me a link to your reference on this policy violation?

It is not a policy, but I've found the original issue: https://github.com/fluttercommunity/plus_plugins/issues/824

**Comment by utkudenis** [comment]
Hello there,
We are selling an affordable package for new members within the app. We were controlling this with the device id so that new accounts would not be opened and taken from the same device. We can't do this right now, do you have any suggestions?

We explained that we got the device id information in the play store and why we got it, and it was accepted.

**Comment by vbuberen** [comment]
Replied in the original issue about removing the AndroidId: https://github.com/fluttercommunity/plus_plugins/issues/824#issuecomment-1199844679

**Comment by nohli** [comment]
A new plugin for getting the Android ID [is published](https://pub.dev/packages/android_id) 🙂

**Comment by TreyThomas93** [comment]
@nohli Why was there a need for another plugin?

**Comment by miquelbeltran** [comment]
Sorry, locking the thread, as commenters should read the original issue https://github.com/fluttercommunity/plus_plugins/issues/824 before asking the same question over and over.

First and foremost, Google discourages the use of the `ANDROID_ID`:  (Avoid using hardware identifiers.)
https://developer.android.com/training/articles/user-data-ids

Secondly, since Android 8.0, the ANDROID_ID is generated for each app, making it not possible for app developers to use it to track across different apps, giving a misleading value if you pretend to use it for user tracking.
https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID

Finally, when reading the `android_id` in native code, Android Studio will warn you to instead use less confidential IDs like the Advertising ID or a custom instant ID.

IMO, if you are using `android_id` in your code, you are probably using it wrong.

We decided that providing this value bundled with all the other device info by default was an unnecessary privacy issue, and that's why it was decided that the `android_id` should be moved to a separated plugin. Many developers use device_info_plus for other reasons than obtaining hardware identifiers, and we specially want to avoid issues when submitting apps to Google Play like the users in #824
